spring.application.name=FastFuriousFood
spring.datasource.url=jdbc:mysql://172.16.0.30:3306/tsr_fastfuriousfood?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=tsr
spring.datasource.password=2diSenai
spring.jpa.hibernate.ddl-auto=update